url: https://jolly-montalcini-8c43e6.netlify.com
baseurl: /

# Site settings
title: Simply Nickie
email: nickie10106@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Simply Nickie
  pic: 1
  position: Freelance Content Creator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title:
      url: #

- name: Simply Confessions
  pic: 2
  position: Blog
  social:
    - title: twitter
      url: #
    - title: instagram
      url: #
    - title: website
      url: www.simplyconfesssions.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/simply_nickie/
  - title: envelope
    url: http://e-mailer.link/100073206607
  - title: whatsapp
    url: https://api.whatsapp.com/send?phone=6597999606&text=Hello!
  - title: paper-plane
    url: https://msng.link/tg/simply_nickie

# Postal address (add as many lines as necessary)
address:
  - line: Singapore

# Build settings
markdown: kramdown
permalink: pretty
